### ISSUE TITLE
[Theos Compiler] Most bundle install paths are broken 

### ISSUE THREAD

**Issue by L1ghtmann** [DragonBuild/dragon#101]
While testing dragon's interpreter against templates generated with theos' nic, I found that a few templates that include a .bundle appear to get treated as preference bundles (/Library/PreferenceLoader/Preferences gets added to the project's directory structure once installed and what would be in the .bundle is instead placed in Resources/).

The relevant templates include:
- control_center_module_11up [install_path: `/Library/ControlCenter/Bundles/$name.bundle`]
- cydget [install_path: `/System/Library/SpringBoardPlugins/$nameLockScreen.bundle`]
- notification_center_widget-7up & notification_center_widget [install_path: `/Library/WeeLoader/Plugins/$name.bundle`]

**Comment by UsrLightmann** [comment]
Also worth noting that flipswitch_switch's are handled properly and preference bundles are handled properly when [these two lines ](https://github.com/DragonBuild/dragon/blob/b909a20e86ca842d074bdfd009c8517f85ad66c6/src/dragongen/theos.py#L175-L176 )are commented out.

**Comment by L1ghtmann** [comment]
Looking at this again now and I don't think it's worth adding support for the legacy templates like cydget or flipswitch, but the control center one and regular bundles should probably be supported.
