### ISSUE TITLE
Dragon won’t install because it “couldn’t build wheel for PyYaml”

### ISSUE THREAD

**Issue by BiassedXD** [DragonBuild/dragon#108]
Any suggestions?

**Comment by L1ghtmann** [comment]
Did you ever end up resolving this?

If not and you're still interested, could you:

1) ensure your python and pip are up-to-date

2) try installing dragon again 

3) if 2) failed, could you share the output of ```pip3 install pyyaml```

**Comment by L1ghtmann** [comment]
Closing due to lack of response. If you're still having issues, feel free to reopen.
