### ISSUE TITLE
[Editor] Add other supported project types to nic

### ISSUE THREAD

**Issue by L1ghtmann** [DragonBuild/dragon#112]
- [x] Preferences
- [x]  Frameworks
- [x] Applications
- [ ] Regular bundles (?)
- [ ] [Others ](https://github.com/DragonBuild/dragon/blob/master/src/dragon/config/types.yml) (?)

**Comment by vr1s** [comment]
Resolved in [aa7dd2b](https://github.com/DragonBuild/dragon/commit/aa7dd2bd2ed94e793a0159ea2a978621e5f5f934) which added the rest of the major project types, along with other minor improvements and bugfixes to it.
