### ISSUE TITLE
'dragon dr' always goes for port 22

### ISSUE THREAD

**Issue by lgariv** [DragonBuild/dragon#37]
`dragon dr` always goes for port 22, regardless of how it was set in `dragon s`:

![Screen Shot 2020-10-07 at 21 03 03](https://user-images.githubusercontent.com/5081484/95370505-88293d80-08e1-11eb-91e0-61b76aeee55b.png)

**Comment by Squidkingdom** [comment]
I can second this, was on my way here to make the same issue.

**Comment by Squidkingdom** [comment]
PR #38 should fix this. @KritantaDev
