### ISSUE TITLE
Have to manually rename [projectname].ninja to build.ninja

### ISSUE THREAD

**Issue by Squidkingdom** [DragonBuild/dragon#40]
A bug exists where when [projectname].ninja is generated, it is not renamed to build.ninja and ninja fails. Can be circumvented by renaming [projectname].ninja manually.

**Comment by KritantaDev** [comment]
Can you reproduce this reliably and provide the steps to do so?

**Comment by Squidkingdom** [comment]
I think I had multiple concurrent builds on dragon installed and all intercommunicating. In troubleshooting something else, I did a fresh install and issue was fixed.
