### ISSUE TITLE
Issue with SDK (at least on linux)

### ISSUE THREAD

**Issue by cxnder** [DragonBuild/dragon#76]
min repro:
```
git clone https://github.com/kritantadev/statusviz
cd statusviz
dragon c b 
````

also shows up in `dragon test` in multiple

is this new?

**Comment by KritantaDev** [comment]
> Possible duplicate of #76.
> 
> `if(@available(iOS 13, *))` causes the following error for both arm64 and arm64e:
> 
> ```
> Undefined symbols for architecture arm64e:
>   "___isOSVersionAtLeast", referenced from:
>       __ZL66_logos_method$Widgets_13$WGWidgetHostingViewController$viewDidLoadP29WGWidgetHostingViewControllerP13objc_selector in Tweak.xm.mm.o
> ```
> 
> Example usage: [here](https://github.com/UsrLightmann/Aeaea/blob/715a4f09d3a3309add9598fe43c05ccdec12fdd4/Tweak.xm#L854)
> 
> Note: swapping out the contents of `iPhoneOS.sdk` in `~/.dragon/sdks/` with another patched sdk does _not_ resolve the issue, at least for me.

- UsrLightmann

**Comment by UsrLightmann** [comment]
Think this may be an issue larger than Dragon . . . have tried debugging for the past couple hours and can't seem to remedy the error any way other than setting the minimum deployment target to >= the version being checked with ```@available```. 

Found an interesting forum post about the issue [here](https://forums.swift.org/t/undefined-symbol-isosversionatleast/29782). Seems it may be a toolchain issue regarding libclang_rt. Sam (Bingner) also encountered an issue with ```@available``` which he described [here](https://github.com/sbingner/llvm-project/issues/1). I assume he's referring to the same static library mentioned above.

**Comment by L1ghtmann** [comment]
Going to close this since it spawns from an issue with `libclang_rt*.a` in the precompiled LLVM/Clang toolchains currently available and not dragon itself.
