### ISSUE TITLE
Dragon is stuck building, when adding arm64e

### ISSUE THREAD

**Issue by MrGcGamer** [DragonBuild/dragon#87]
https://user-images.githubusercontent.com/32813275/132949327-a2a189f0-0050-46e8-bb54-c604a62d40e6.mp4

**Comment by MrGcGamer** [comment]
well as you can see this is on macOS, version 11.6 and I just used theos for that project instead and that did the job.

**Comment by dlevi309** [comment]
Yeah, I do see that, but regardless of the platform I haven’t seen anyone else have this issue. Maybe I need to update my local version of theos

**Comment by vr1s** [comment]
Is this still reproducible on the latest version?

**Comment by MrGcGamer** [comment]
doesn't seem to be the case (Had to rebuild that project setup, but still)

**Comment by vr1s** [comment]
Alright, closing this for now. We should be pinned to latest dm.pl and it appears the issue has been resolved there.
