### ISSUE TITLE
Permission denied when trying to build tweak in WSL2 (Ubuntu)

### ISSUE THREAD

**Issue by F0lkl0re** [DragonBuild/dragon#90]
When compiling a tweak with dragon on wsl, it is unable to build due to not enough perms
Any workaround for this?

![image](https://user-images.githubusercontent.com/51024076/133337434-cec06752-d57b-4628-8ead-6bdd6dfa8c1f.png)

**Comment by UsrLightmann** [comment]
@F0lkl0re did you ever get this resolved?

**Comment by F0lkl0re** [comment]
> 
> 
> @F0lkl0re did you ever get this resolved?

Nope. I just scratched wsl because wsl is a mess and used my dualboot again

**Comment by KritantaDev** [comment]
For future reference: afaik this looks like a toolchain issue
