### ISSUE TITLE
[Theos Compiler] `target` version stuck at 10.0 irrespective of Makefile deployment target

### ISSUE THREAD

**Issue by L1ghtmann** [DragonBuild/dragon#95]
No matter what the target version is set to in the makefile, Dragon seems to always build for 10.0+.

```
-miphoneos-version-min=10.0 
-target arm64-apple-ios10.0
```

Occurs with a standard Unix makefile ~~and with a DragonMake file with `targetvers:` set~~.

**Comment by UsrLightmann** [comment]
Also, somewhat related, I don't think you need the `miphoneos-version-min` flag with the `ios<version>` triple. otool shows it being set to whatever version the target flag specifies in the absence of the `miphoneos-version-min` flag.
